### ISSUE TITLE
ต่อ com port ไม่ได้

### ISSUE THREAD

**Issue by koson** [Special-Topic-2567/MQTT#2]
กด flash  แล้วขึ้นแบบนี้

[/Flash]
[Build]
Project build complete. To flash, run:
ESP-IDF: Flash your project in the ESP-IDF Visual Studio Code Extension
or in a ESP-IDF Terminal:
idf.py flash
or
idf.py -p PORT flash
or
python -m esptool --chip esp32 -b 460800 --before default_reset --after hard_reset  --port COM5 write_flash --flash_mode dio --flash_size 2MB --flash_freq 40m 0x1000 bootloader/bootloader.bin 0x10000 mqtt_tcp.bin 0x8000 partition_table/partition-table.bin 
or from the "d:\GithubRepos\ENGEDU\Special_Topics_2567\tcp\build" directory
python -m esptool --chip esp32 -b 460800 --before default_reset --after hard_reset write_flash "@flash_args"
[/Build]
[Flash]
Flash Done ⚡️
Failed to flash because of some unusual error. Check Terminal for more details
Flash has finished. You can monitor with ESP-IDF: Monitor your device command

**Comment by VisawaPRO** [comment]
ไม่ได้เสียบ comport ครับ ลองเช็คดูว่าเสียบสายรึยังหรือสายมีปัญหา

**Comment by koson** [comment]
ได้แล้วครับ ขอบคุณมากครับ
